### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by CleverSource** [Infraxion/modis#15]
I think that there should be some moderation features on the UI to control and have like !warn and it gives them a warning and at 3 warnings they get kicked and also like a temp ban and when you ban them like a 3 day ban and after 3 days the bot says hey u can come back and gives a discord.gg/ invite to the server thru dm's and also have like !ban, !kick, !mute, !warn, moderation logs etc. :D

**Comment by Infraxion** [comment]
Added by @YtnomSnrub, will be in next release c:
