### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by Gh0stR1pp3r** [Infraxion/modis#34]
Any possibility of getting an official docker image?

**Comment by Infraxion** [comment]
Hi there, not sure what you mean by docker image?

**Comment by Gh0stR1pp3r** [comment]
Docker is a container platform - each app runs in a dedicated container created from image. Examples of images here - https://hub.docker.com/. For small home servers, docker is a godsend.

**Comment by Infraxion** [comment]
Ahh, I see. This looks like something that we might do in the future if there is enough demand for it, but for now, we'd like to focus on increasing Modis' stability, finishing our documentation, and promoting Modis to draw in more developers.

Speaking of developers, you're welcome to clone and give a Docker image a go yourself!
